### PR TITLE
fix: renaming file for the example with `verify-revision-deployment`

### PR DESCRIPTION
**Pull request by patoroco**
Renaming the file for fixing a typo in its name that appears on the docs:
https://circleci.com/developer/orbs/orb/circleci/aws-ecs#usage-verify-revision-deplopyment

image

### CODE REVIEW

**Comment by patoroco** [comment]
@brivu could you check this one?

**Comment by brivu** [comment]
Hi @patoroco - I tried merging your `PR` but you have lint error when I ran the tests. I went ahead and added this fix in PR #202. Thank you for your contribution!

**Comment by jorgemaroto-eb** [comment]
@brivu don't worry, happy it finally was fixed :)

**Comment by patoroco** [comment]
@brivu don't worry, happy it finally was fixed :)

**Pull request closed without merging**
