### PR TITLE
feat: adding `service-name` param to specify service name

### PR DESCRIPTION
**Pull request by stringbeans**
prior to this, `family` was assuming both the service and task definition were named the same

### CODE REVIEW

**Comment by iynere** [comment]
thank you !! @stringbeans 

@lokst can you take a look at this ? you know this orb better than i do, i think

if it's good, i'll add tests for this edge case

**Comment by lokst** [comment]
Thank you @stringbeans !
@iynere Yes I'll be taking a look!

**Comment by stringbeans** [comment]
just linking the issue: https://github.com/CircleCI-Public/aws-ecs-orb/issues/5

**Comment by lokst** [comment]
Hi @stringbeans , I've just pushed a one liner change to the master branch to ensure the most current development version of the orb is used for tests, could you pull it into your branch?

I tested your branch and found that the service-name parameter is treated as a mandatory parameter. (https://circleci.com/gh/CircleCI-Public/aws-ecs-orb/776?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

It could be made an optional parameter by adding a `default` key with an empty string value (See: https://circleci.com/docs/2.0/reusing-config/#parameter-syntax)

**Comment by stringbeans** [comment]
@lokst thanks for the review! changes have been applied.. lemme know if theres anything else :)

**Comment by lokst** [comment]
Thanks @stringbeans, we'll run these through some tests and get them merged asap! :)

**Comment by lokst** [comment]
@stringbeans circleci/aws-ecs@0.0.5 has been published with these changes, thank you for your work!

**Comment by stringbeans** [comment]
thanks @lokst @iynere !! 🎆

**Pull request merged**
