### PR TITLE
Add command support for --cli-input-json

### PR DESCRIPTION
**Pull request by a10waveracer**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

This PR addresses #20. I like having the ability to keep my task definitions in my source code and simply updating the task definition based upon that .json.

### Description

Add the ability to update task definitions based upon a stored `.json` file

This PR was initially https://github.com/CircleCI-Public/aws-ecs-orb/pull/47 but I screwed the rebase, so here we are....

### CODE REVIEW

**Comment by a10waveracer** [comment]
This PR extends #47 but also addresses comments by @lokst:

- Filepaths can be given as absolute or relative
- The name has been changed to one of the suggested names
- Merged in master (oops....)
- Omit checkout/install/configure
- Added a job version in addition to the command
- Added an example

Sorry for messing up the previous PR.

**Comment by lokst** [comment]
@a10waveracer Thank you for this! We'll review this soon 🙂

**Comment by a10waveracer** [comment]
@lokst Thank you! It only took me four months to get around to this, so I’ll be understanding of a delayed response 🙃

**Comment by a10waveracer** [comment]
@lokst Thank you! I appreciate you adding the test.

**Comment by lokst** [comment]
@a10waveracer Your changes are now available in `circleci/aws-ecs@1.1.0` , thanks for your contribution! 🎉

**Pull request merged**
